// =============================================================================
// @o/operator/brief — the brief inbox generator
// =============================================================================
// This is what runs when the operator notices a client-relevant event
// happened. It produces a brief_entries row with:
//   - a plain-English title
//   - a 2-sentence AI summary
//   - a CTA (button label + href)
//
// One entry per event. The client_brief_summary action (in actions.ts)
// reads these entries and writes a weekly digest for the client.

import { eq, and, desc, gte, isNull, count } from "drizzle-orm";
import { getDb } from "@o/db/client";
import { briefEntries, contacts, photoJobs, photoVariations, invoices, payments, milestones, files, projects, timeEntries } from "@o/db/schema";
import { callText, pickModel } from "./llm";
import { logger } from "@o/logger";
import { z } from "zod";
import { randomUUID } from "crypto";

// -----------------------------------------------------------------------------
// Event producers — one function per event kind
// -----------------------------------------------------------------------------
// Each `onXxx` function is called by the runner (or by application code)
// when a client-relevant event happens. The function gathers context and
// creates one or more brief_entries rows for the affected client(s).
//
// The summary text is generated by GPT. It's not magic — it's the LLM
// turning structured data into 2 sentences a human wants to read.

export async function onPhotoJobReady(orgId: string, photoJobId: string) {
  const db = getDb();
  const [job] = await db.select().from(photoJobs).where(eq(photoJobs.id, photoJobId)).limit(1);
  if (!job) return;

  // Find the contact — the uploader is the client in most cases
  const contactId = await resolveContactForOrg(orgId, job.uploadedBy);
  if (!contactId) {
    logger.warn("Photo job ready but no contact found", { orgId, photoJobId });
    return;
  }

  const [vStats] = await db.select({ n: count(), total: photoJobs.totalCostUsd })
    .from(photoJobs).where(eq(photoJobs.id, photoJobId));

  // Group all the variations of this job under one groupId so the feed
  // shows it as a single card even if the worker reports them separately
  const groupId = `grp_photo_${photoJobId}`;

  const summary = await generateSummary({
    context: `A photo job finished processing.`,
    facts: [
      `Filename: ${job.filename}`,
      `Variations produced: ${(job.requestedVariations ?? []).length}`,
      `Total cost: $${(job.totalCostUsd ?? 0).toFixed(2)}`,
      `Caption: ${job.caption ?? "(none)"}`,
    ],
    instruction: "Write 2 sentences. Sentence 1: their photos are ready, mention the count and cost. Sentence 2: invite them to view and download. Don't use exclamation marks.",
  });

  await db.insert(briefEntries).values({
    id: `brf_${randomUUID()}`,
    orgId,
    contactId,
    kind: "photo_ready",
    priority: "normal",
    subjectType: "photo_job",
    subjectId: photoJobId,
    title: `Photos ready: ${job.filename}`,
    summary,
    actionLabel: "View variations",
    actionHref: `/photos`,
    dayBucket: new Date().toISOString().slice(0, 10),
    groupId,
  });
}

export async function onInvoiceSent(orgId: string, invoiceId: string) {
  const db = getDb();
  const [inv] = await db.select().from(invoices).where(eq(invoices.id, invoiceId)).limit(1);
  if (!inv) return;
  const contactId = inv.contactId;
  if (!contactId) return;

  const summary = await generateSummary({
    context: "A new invoice was sent to the client.",
    facts: [
      `Invoice number: ${inv.number}`,
      `Amount: ${formatMoney(inv.amount, inv.currency)}`,
      `Due: ${inv.dueDate}`,
    ],
    instruction: "Write 2 sentences. Sentence 1: confirm the invoice was sent, state amount and due date. Sentence 2: tell them how to pay or who to contact. Don't use exclamation marks.",
  });

  await db.insert(briefEntries).values({
    id: `brf_${randomUUID()}`,
    orgId,
    contactId,
    kind: "invoice_sent",
    priority: "normal",
    subjectType: "invoice",
    subjectId: invoiceId,
    title: `Invoice ${inv.number} · ${formatMoney(inv.amount, inv.currency)}`,
    summary,
    actionLabel: "View invoice",
    actionHref: `/invoices/${inv.id}`,
    dayBucket: new Date().toISOString().slice(0, 10),
  });
}

export async function onInvoicePaid(orgId: string, paymentId: string) {
  const db = getDb();
  const { payments } = await import("@o/db/schema");
  const [payment] = await db.select().from(payments).where(eq(payments.id, paymentId)).limit(1);
  if (!payment) return;
  if (!payment.invoiceId) return;
  const [inv] = await db.select().from(invoices).where(eq(invoices.id, payment.invoiceId)).limit(1);
  if (!inv) return;
  const contactId = inv.contactId;
  if (!contactId) return;

  const summary = `Thanks — payment of ${formatMoney(payment.amount, payment.currency)} for ${inv.number} received.${payment.method === "crypto" ? ` Settled on-chain at ${payment.txHash?.slice(0, 10)}…` : ""} A receipt is in your portal.`;

  await db.insert(briefEntries).values({
    id: `brf_${randomUUID()}`,
    orgId,
    contactId,
    kind: "invoice_paid",
    priority: "low",
    subjectType: "invoice",
    subjectId: inv.id,
    title: `Paid · ${inv.number} · ${formatMoney(payment.amount, payment.currency)}`,
    summary,
    actionLabel: "Download receipt",
    actionHref: `/invoices/${inv.id}`,
    dayBucket: new Date().toISOString().slice(0, 10),
  });
}

export async function onMilestoneComplete(orgId: string, milestoneId: string) {
  const db = getDb();
  const [m] = await db.select().from(milestones).where(eq(milestones.id, milestoneId)).limit(1);
  if (!m) return;
  const [project] = await db.select().from(projects).where(eq(projects.id, m.projectId)).limit(1);
  if (!project?.clientId) return;

  const summary = await generateSummary({
    context: `A project milestone was marked complete.`,
    facts: [
      `Milestone: ${m.name}`,
      `Project: ${project.name}`,
      `Status: ${m.status}`,
    ],
    instruction: "Write 2 sentences. Sentence 1: the milestone is done, name it. Sentence 2: what's next, or invite them to review. Don't use exclamation marks.",
  });

  await db.insert(briefEntries).values({
    id: `brf_${randomUUID()}`,
    orgId,
    contactId: project.clientId,
    kind: "milestone_complete",
    priority: "high",
    subjectType: "milestone",
    subjectId: m.id,
    title: `Done: ${m.name}`,
    summary,
    actionLabel: "View project",
    actionHref: `/projects/${project.id}`,
    dayBucket: new Date().toISOString().slice(0, 10),
  });
}

export async function onFileShared(orgId: string, fileId: string) {
  const db = getDb();
  const [f] = await db.select().from(files).where(eq(files.id, fileId)).limit(1);
  if (!f) return;
  if (!f.contactId) return;  // not shared with a contact

  const summary = await generateSummary({
    context: "A file was shared with the client.",
    facts: [
      `Filename: ${f.name}`,
      `Size: ${(f.sizeBytes / 1024).toFixed(0)} KB`,
      `Type: ${f.contentType}`,
    ],
    instruction: "Write 1 sentence describing what was shared and inviting them to download. Don't use exclamation marks.",
  });

  await db.insert(briefEntries).values({
    id: `brf_${randomUUID()}`,
    orgId,
    contactId: f.contactId,
    kind: "file_shared",
    priority: "normal",
    subjectType: "file",
    subjectId: f.id,
    title: `New file: ${f.name}`,
    summary,
    actionLabel: "Download",
    actionHref: `/files/${f.id}`,
    dayBucket: new Date().toISOString().slice(0, 10),
  });
}

export async function onTimeLogged(orgId: string, timeEntryId: string) {
  // Only generate a brief entry for time entries on projects the client
  // cares about, and only if it's the first entry of the day on a project
  // (so we don't spam the client with 30 entries for one 4-hour session).
  const db = getDb();
  const [entry] = await db.select().from(timeEntries).where(eq(timeEntries.id, timeEntryId)).limit(1);
  if (!entry) return;
  const [project] = await db.select().from(projects).where(eq(projects.id, entry.projectId)).limit(1);
  if (!project?.clientId) return;

  // De-dupe: only create an entry if the most recent brief entry for this
  // project on this day is more than 4 hours old
  const today = new Date().toISOString().slice(0, 10);
  const recent = await db.select().from(briefEntries)
    .where(and(
      eq(briefEntries.contactId, project.clientId),
      eq(briefEntries.subjectType, "project"),
      eq(briefEntries.subjectId, project.id),
      eq(briefEntries.dayBucket, today),
    ))
    .orderBy(desc(briefEntries.createdAt))
    .limit(1);
  if (recent.length > 0) {
    const lastTime = new Date(recent[0].createdAt).getTime();
    if (Date.now() - lastTime < 4 * 60 * 60 * 1000) return;  // recent entry exists
  }

  const summary = await generateSummary({
    context: "Time was logged on a client project.",
    facts: [
      `Hours: ${(entry.hours ?? 0).toFixed(1)}`,
      `Project: ${project.name}`,
      `Description: ${entry.description ?? "(no description)"}`,
    ],
    instruction: "Write 1 sentence telling the client work happened on their project and giving a sense of what. Don't use exclamation marks. Don't promise anything.",
  });

  await db.insert(briefEntries).values({
    id: `brf_${randomUUID()}`,
    orgId,
    contactId: project.clientId,
    kind: "time_logged",
    priority: "low",
    subjectType: "project",
    subjectId: project.id,
    title: `Work on ${project.name}`,
    summary,
    actionLabel: "View project",
    actionHref: `/projects/${project.id}`,
    dayBucket: today,
  });
}

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

async function generateSummary(args: { context: string; facts: string[]; instruction: string }): Promise<string> {
  const system = `You write 1-2 sentence summaries for a creative operations company's client portal. The summaries are factual, specific, and never use exclamation marks. They tell the client what happened and what they can do next. Never start with "Great" or "Awesome" or any enthusiastic opener. Never make promises about future work. Just the facts and the next step.`;
  const user = `Context: ${args.context}

Facts:
${args.facts.map((f) => `- ${f}`).join("\n")}

Instruction: ${args.instruction}

Write the summary. Just the summary — no preamble, no labels.`;

  try {
    const result = await callText({
      model: pickModel("draft"),
      system,
      user,
      temperature: 0.4,
      maxTokens: 200,
    });
    return result.text.trim();
  } catch (err) {
    // LLM failed — fall back to a static fact-based summary so the feed
    // doesn't go empty. Better a boring one-liner than no entry.
    logger.warn("Brief summary LLM failed, using fallback", { err: String(err) });
    return args.facts.join(". ") + ".";
  }
}

async function resolveContactForOrg(orgId: string, personId: string): Promise<string | null> {
  // The uploader might be a staff person (the photographer), not the client.
  // In that case, find the most recent contact that interacted with this
  // person's uploads. For v1, we use a simple heuristic: the most recently
  // active contact in this org.
  const db = getDb();
  const [contact] = await db.select().from(contacts)
    .where(eq(contacts.orgId, orgId))
    .orderBy(desc(contacts.updatedAt))
    .limit(1);
  return contact?.id ?? null;
}

function formatMoney(cents: number, currency: string): string {
  const amount = cents / 100;
  return new Intl.NumberFormat("en-US", { style: "currency", currency: currency || "USD" }).format(amount);
}
